gokalpgoren
    amd64:
        docker build -t gokalpgoren/face_recognition_pytorch:v1.0.1-amd64 .
        docker run -it --restart unless-stopped --name face_recognition_pytorch-instance --net host -e TZ=Europe/Istanbul --gpus all -e NVIDIA_DRIVER_CAPABILITIES=all gokalpgoren/face_recognition_pytorch:v1.0.1-arm64v8
